### ISSUE TITLE
Hero not centered on mobile

### ISSUE THREAD

**Issue by tylermenezes** [codeday/www-event#39]
When viewing on mobile (or on the desktop if you make the window really narrow), the hero text at the top of an event page is not centered. For example, on [https://event.codeday.org/en-US/seattle](https://event.codeday.org/en-US/seattle):

![image](https://user-images.githubusercontent.com/173390/222573992-2b4d6eba-c91a-4817-9b01-d769d326c457.png)

It would make more sense to center this when viewing on mobile (but NOT on desktop).

This site uses Chakra UI; some good documentation on changing a property based on window size in Chakra UI: [https://chakra-ui.com/docs/styled-system/responsive-styles#the-object-syntax](https://chakra-ui.com/docs/styled-system/responsive-styles#the-object-syntax)

**Comment by alisonfung** [comment]
CTI Team H is working on this.
